# Álgebra Linear Computacional

Algoritmo QR

Profs. Alexandre Salles da Cunha e Ana Paula Couto da Silva

In [7]:
import numpy as np
from numpy.linalg import qr


In [5]:
A1 = np.array([[85, 102,70,129,137], 
              [102,167, 85,157,189],[70,85,110,91,151],[129,157,91,272,218],[137,189,151,218,267]])
p = [1, 2, 5, 8, 10, 15, 20,30]
print ('Matriz Simétrica')
for i in range(30):
    q, r = qr(A1)
    A1 = np.dot(r, q)
    if i+1 in p:
        print(f'Iteration {i+1}:')
        print(A1)

Matriz Simétrica
Iteration 1:
[[ 7.58078324e+02  8.99241394e+00  1.18060289e+01  2.56882887e+01
  -2.57976893e-02]
 [ 8.99241394e+00  4.29254853e+01  1.07470896e+01 -1.45692839e+01
  -6.06181271e-03]
 [ 1.18060289e+01  1.07470896e+01  8.08312675e+01 -1.54288608e+01
  -1.63333884e-02]
 [ 2.56882887e+01 -1.45692839e+01 -1.54288608e+01  1.91328368e+01
  -7.47217477e-03]
 [-2.57976893e-02 -6.06181271e-03 -1.63333884e-02 -7.47217477e-03
   3.20866217e-02]]
Iteration 2:
[[ 7.59261108e+02  2.85270024e-01  7.55149371e-01  3.58318967e-01
   1.09057844e-06]
 [ 2.85270024e-01  5.77672803e+01  2.13211111e+01 -3.38243130e+00
   3.96139357e-06]
 [ 7.55149371e-01  2.13211111e+01  7.39455033e+01 -7.31738823e-01
   4.98592274e-06]
 [ 3.58318967e-01 -3.38243130e+00 -7.31738823e-01  9.99403678e+00
   3.45658078e-05]
 [ 1.09057844e-06  3.96139357e-06  4.98592273e-06  3.45658078e-05
   3.20717181e-02]]
Iteration 5:
[[ 7.59262245e+02  1.20808570e-03  2.42323362e-04  7.59848380e-07
  -3.46214573e-16]
 [ 1.20

In [6]:
A2 = np.array([[10,4,9,8,2], 
              [8,1,8,7,7],[5,3,6,1,9],[7,4,4,3,5],[0,2,9,7,3]])
p = [1, 2, 5, 8, 10, 15, 20,30]
print ('Matriz Não Simétrica')
for i in range(30):
    q, r = qr(A2)
    A2 = np.dot(r, q)
    if i+1 in p:
        print(f'Iteration {i+1}:')
        print(A2)

Matriz Não Simétrica
Iteration 1:
[[ 22.27731092 -11.84603223   5.10654821   2.69112544   2.05655287]
 [ -4.00373109   1.59857959  -2.53618705  -3.27000485   2.21792558]
 [  5.78428056  -7.18353361  -0.89765507   5.14812184  -3.48226483]
 [ -1.58194859  -2.23168636   6.27513282  -0.4911526    1.25129682]
 [  0.           2.23958319  -2.8531199    0.79518429   0.51291716]]
Iteration 2:
[[25.3776899   1.09369054 -7.58809147  7.75850027 -0.4688953 ]
 [ 1.56347392  3.61886833 -1.84608164  5.18223863  2.03363933]
 [-1.89054605 -2.71810365 -6.33631567 -2.68497865  1.56192773]
 [-0.26487517  3.48238123 -3.43214619 -0.95396849  0.87799838]
 [ 0.          0.62548727 -0.35525001 -0.48442733  1.29372592]]
Iteration 5:
[[ 2.60188414e+01  5.46410488e+00  8.20720126e-01  7.87908647e+00
   2.14389171e+00]
 [ 9.64711151e-03  5.09103439e+00  4.83863898e+00 -7.33313407e-01
  -6.41969993e-01]
 [ 5.22290448e-02  4.29276463e+00 -6.07557378e+00  2.00697699e+00
  -2.23230408e+00]
 [ 6.34815042e-04 -5.8202060