## Álgebra Linear Computacional
### Erros numéricos 
Profs. Alexandre Salles da Cunha e Ana Paula Couto da Silva

In [3]:
import numpy as np
import math

In [55]:
n = 18
x = np.zeros(n,dtype = 'float64')
f1 = np.zeros(n,dtype = 'float64')
f2 = np.zeros(n,dtype = 'float64')
for i in range(n):
    x[i] = np.power(0.1,i+1)
    f1[i] = (math.exp(x[i])-math.exp(-2.*x[i]))/x[i]
    f2[i] = (x[i]-math.sin(x[i]))/(np.power(x[i],3.0))



In [56]:
x,f1,f2

(array([1.e-01, 1.e-02, 1.e-03, 1.e-04, 1.e-05, 1.e-06, 1.e-07, 1.e-08,
        1.e-09, 1.e-10, 1.e-11, 1.e-12, 1.e-13, 1.e-14, 1.e-15, 1.e-16,
        1.e-17, 1.e-18]),
 array([2.86440165, 2.98514938, 2.9985015 , 2.99985001, 2.999985  ,
        2.9999985 , 2.99999985, 2.99999997, 3.00000003, 3.00000025,
        3.00000025, 3.00004466, 2.99871239, 2.99760217, 3.10862447,
        2.22044605, 0.        , 0.        ]),
 array([0.16658335, 0.16666583, 0.16666666, 0.16666666, 0.16666728,
        0.16665373, 0.17205357, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ]))

In [57]:
def AvaliaF2(x,kmax,tol):
    v = 1.0/6.0
    k = 2
    convergiu = 0
    while (k <= kmax) & (convergiu == 0):
        f = math.factorial(2*k+1)
        termo = np.power(-1,k)*np.power(x,2*(k-1))/f
        v = v - termo
        if abs(termo) <= tol:
            convergiu = 1
        print('k = ',k,'v = ',"{:.10f}".format(v),\
              '|termo| = ',"{:.10E}".format(abs(termo)))
        k = k + 1
    
    

In [58]:
AvaliaF2(.5,8,1.0e-10)

k =  2 v =  0.1645833333 |termo| =  2.0833333333E-03
k =  3 v =  0.1645957341 |termo| =  1.2400793651E-05
k =  4 v =  0.1645956911 |termo| =  4.3058311287E-08
k =  5 v =  0.1645956912 |termo| =  9.7859798381E-11


In [24]:
AvaliaF2(1.0E-16,8,1.0e-10)

k =  2 v =  0.1666666667 |termo| =  8.3333333333E-35


In [34]:
def PrecisaodaMaquina():
    a = 1.0
    u = 1.0
    b = a + u
    k = 0
    while (b != a):
        u = u / 2.0
        b = a + u
        k = k + 1
    r = a + u
    p = 2*u
    print('r = ',r,'k = ',k,'Precisao = ',"{:.16E}".format(p))
    return r,k,p

In [35]:
r,k,p = PrecisaodaMaquina()

r =  1.0 k =  53 Precisao =  2.2204460492503131E-16


O valor que calculamos é disponível para acesso do usuário.

In [39]:
print(np.finfo('float64').eps)
print(np.finfo('float').eps)
print(np.finfo('float32').eps)

2.220446049250313e-16
2.220446049250313e-16
1.1920929e-07


In [43]:
v = (1.0 + 0.5*np.finfo('float64').eps) - 1.0
print(v)

0.0
