## Álgebra Linear Computacional
### Fatorações básicas (Eliminação de Gauss, Pivoteamento Parcial e Cholesky)
#### Profs. Alexandre Salles da Cunha e Ana Paula Couto da Silva

In [1]:
import numpy as np
import math


#### Para explorar o conteúdo da biblioteca np (ou qualquer outra), digite np. e complete com "tab" para que o sistema ofereça as opções

In [2]:
A = np.array([[2,1,1,0],[4,3,3,1],[8,7,9,5],[6,7,9,8]],dtype = 'float64')
R = np.random.random((4,4))
I = np.eye((4))
b = np.array([2,3,3,9],dtype='float64')
x = np.linalg.solve(R,b)
n = len(A)


In [3]:
def EliminacaoGauss(A):
    n = len(A)
    #U = A (esta instrucao difere da abaixo .copy(A))
    U = np.copy(A)
    L = np.eye(n)
    for j in range(0,n-1):
        for i in range(j+1,n):
            L[i,j] = U[i,j]/U[j,j]
            U[i,j:n] = U[i,j:n] - L[i,j]*U[j,j:n]
    return U,L

In [4]:
U,L = EliminacaoGauss(A)

In [5]:
print(U)
print(L)

[[2. 1. 1. 0.]
 [0. 1. 1. 1.]
 [0. 0. 2. 2.]
 [0. 0. 0. 2.]]
[[1. 0. 0. 0.]
 [2. 1. 0. 0.]
 [4. 3. 1. 0.]
 [3. 4. 1. 1.]]


In [6]:
def EliminacaoGauss_Outer(A):
    # nao implementa troca de linhas
    n = len(A)
    U = np.full((n,n),0.0)
    L = np.eye(n)
    AC = np.copy(A)
    for j in range(0,n-1):
        L[j+1:,j] = AC[j+1:,j]/AC[j,j]
        U[j,j:]    = AC[j,j:]
        AC[j+1:,j+1:] = AC[j+1:,j+1:] - np.outer(L[j+1:,j],U[j,j+1:])
        #print(AC[j+1:,j+1:])
        #print(U)
    U[n-1,n-1] = AC[n-1,n-1]
    #print(L)
    #print(U)
    return L,U

In [7]:
L,U = EliminacaoGauss_Outer(A)
print(np.matmul(L,U)-A)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
def DeterminaLinhaPivot(U,j):
    vmax = abs(U[j,j])
    jmax = j
    for i in range(j+1,len(U)):
        if abs(U[i,j]) > vmax:
            vmax = abs(U[i,j])
            jmax = i
    return jmax

def Troca(U,L,j,p,pivot):
    for i in range(0,j):
        # parte em L
        t = L[j,i]
        L[j,i] = L[p,i]
        L[p,i] = t
    for i in range(j,len(U)):
        # parte em U
        t = U[j,i]
        U[j,i] = U[p,i]
        U[p,i] = t
    
    t = pivot[j]
    pivot[j] = pivot[p]
    pivot[p] = t
    

def EliminacaoGaussPivoteamento(A):
    n = len(A)
    U = np.copy(A)
    L = np.eye(n)
    pivot = np.arange(0,n,1)
    for j in range(0,n-1):
        p = DeterminaLinhaPivot(U,j)
        #print('pivot',p)
        if (p != j):
            Troca(U,L,j,p,pivot)
        for i in range(j+1,n):
            L[i,j] = U[i,j]/U[j,j]
            U[i,j:n] = U[i,j:n] - L[i,j]*U[j,j:n]
    return L,U,pivot

In [9]:
L,U,pivot = EliminacaoGaussPivoteamento(A)
print(L)
print(U)
print(pivot)

[[ 1.          0.          0.          0.        ]
 [ 0.75        1.          0.          0.        ]
 [ 0.5        -0.28571429  1.          0.        ]
 [ 0.25       -0.42857143  0.33333333  1.        ]]
[[ 8.          7.          9.          5.        ]
 [ 0.          1.75        2.25        4.25      ]
 [ 0.          0.         -0.85714286 -0.28571429]
 [ 0.          0.          0.          0.66666667]]
[2 3 1 0]


In [10]:
def EliminacaoGauss_Outer_Pivotal(A):
    # implementa pivoteamento parcial na visao por colunas
    n = len(A)
    pivot = np.arange(0,n,1)
    U = np.full((n,n),0.0)
    L = np.eye(n)
    AC = np.copy(A)
    for j in range(0,n-1):
        
        p = DeterminaLinhaPivot(AC,j)
        if (p != j):
            Troca(AC,L,j,p,pivot)
                
        L[j+1:,j] = AC[j+1:,j]/AC[j,j]
        U[j,j:]    = AC[j,j:]
        AC[j+1:,j+1:] = AC[j+1:,j+1:] - np.outer(L[j+1:,j],U[j,j+1:])
        #print(AC[j+1:,j+1:])
        #print(U)
    U[n-1,n-1] = AC[n-1,n-1]
    #print(L)
    #print(U)
    return L,U,pivot

In [11]:
L,U,pivot = EliminacaoGauss_Outer_Pivotal(A)
print(L)
print(U)
print(pivot)

[[ 1.          0.          0.          0.        ]
 [ 0.75        1.          0.          0.        ]
 [ 0.5        -0.28571429  1.          0.        ]
 [ 0.25       -0.42857143  0.33333333  1.        ]]
[[ 8.          7.          9.          5.        ]
 [ 0.          1.75        2.25        4.25      ]
 [ 0.          0.         -0.85714286 -0.28571429]
 [ 0.          0.          0.          0.66666667]]
[2 3 1 0]


In [12]:
import scipy
import scipy.linalg
perm,l,u = scipy.linalg.lu(A)
print(l)
print(u)
print(perm)

[[ 1.          0.          0.          0.        ]
 [ 0.75        1.          0.          0.        ]
 [ 0.5        -0.28571429  1.          0.        ]
 [ 0.25       -0.42857143  0.33333333  1.        ]]
[[ 8.          7.          9.          5.        ]
 [ 0.          1.75        2.25        4.25      ]
 [ 0.          0.         -0.85714286 -0.28571429]
 [ 0.          0.          0.          0.66666667]]
[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [13]:
def ResolveTriangInf(L,b,p):
    n = len(L)
    y = np.zeros(n,dtype = 'float64')
    for i in range(0,n):
        y[i] = b[p[i]] - np.matmul(L[i,:i],y[:i])
        if L[i,i] != 0.0:
            y[i] = y[i]/L[i,i]
    return y

def ResolveTriangSup(U,b):
    n = len(U)
    x = np.zeros(n,dtype = 'float64')
    for i in range(n-1,-1,-1):
        x[i] = b[i] - np.matmul(U[i,i+1:],x[i+1:])
        if (U[i,i] != 0.0):
            x[i] = x[i] / U[i,i]
    return x    

def ResolveSistemaLinear(A,b):
    L,U,pivot = EliminacaoGaussPivoteamento(A)
    y = ResolveTriangInf(L,b,pivot)
    x = ResolveTriangSup(U,y)
    return x

In [14]:
y = ResolveTriangInf(L,b,pivot)
print(b)
print(pivot)
print(y)

[2. 3. 3. 9.]
[2 3 1 0]
[3.         6.75       3.42857143 3.        ]


In [15]:
Y = range(len(L)-1,-1,-1)
for i in Y:
    print(i)

3
2
1
0


In [16]:
x = ResolveSistemaLinear(A,b)
print(x)

[ 3.7500000e+00  2.0301221e-15 -5.5000000e+00  4.5000000e+00]


In [17]:
ATA = A @ A.transpose()
print(ATA)

[[  6.  14.  32.  28.]
 [ 14.  35.  85.  80.]
 [ 32.  85. 219. 218.]
 [ 28.  80. 218. 230.]]


In [18]:
def Cholesky_Outer(R):
    n = len(R)
    for j in range(0,n):
        if (R[j,j] > 0.0):
            R[j,j] = math.sqrt(R[j,j])
            R[j,j+1:] = R[j,j+1:]/R[j,j]
            R[j+1:,j+1:] = R[j+1:,j+1:] - np.outer(R[j,j+1:],R[j,j+1:])
    return np.triu(R)        
            
        

In [19]:
R = ATA.copy()
Fator = Cholesky_Outer(R)
print(Fator)

[[ 2.44948974  5.71547607 13.06394529 11.43095213]
 [ 0.          1.52752523  6.7647546   9.60158717]
 [ 0.          0.          1.60356745  2.3162641 ]
 [ 0.          0.          0.          1.33333333]]


In [20]:
Fator2 = np.linalg.cholesky(ATA)
print(Fator2)
AR = np.matmul(Fator2,Fator)
print(AR)

[[ 2.44948974  0.          0.          0.        ]
 [ 5.71547607  1.52752523  0.          0.        ]
 [13.06394529  6.7647546   1.60356745  0.        ]
 [11.43095213  9.60158717  2.3162641   1.33333333]]
[[  6.  14.  32.  28.]
 [ 14.  35.  85.  80.]
 [ 32.  85. 219. 218.]
 [ 28.  80. 218. 230.]]
